In [1]:
import numpy as np

In [2]:
z = np.zeros(10)
print(z)
z=np.arange(10,50)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
print(
    np.arange(9).reshape(3,3),
    np.eye(3),
    np.random.random((3,3,3))
)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [[[0.72595523 0.91297392 0.68988217]
  [0.38967037 0.24624807 0.73839573]
  [0.06285172 0.29413426 0.97783614]]

 [[0.80327362 0.82108831 0.93036127]
  [0.65204177 0.46042197 0.40937025]
  [0.80024483 0.31088576 0.48997457]]

 [[0.75016035 0.93102935 0.19109023]
  [0.20657005 0.12709435 0.44523804]
  [0.8075186  0.53883688 0.24342762]]]
